### ISSUE TITLE
Spectators can pick stuff up and drop stuff as well

### ISSUE THREAD

**Issue by Anonymous3-a** [EISHU-MT/block_assault#3]
If I die, I'm able to pick up my stuff that I dropped and, for example, give it to a teammate.
Video coming next time I die.

**Comment by Python-Sargent** [comment]
This bug used to happen before the rename too. The items weren't cleared off the ground and inv until a new match started.
I don't think it's possible to stop the player from picking the items up, but you can immediately drop them when they are picked up.

**Comment by nisep9** [comment]
Bug will be fixed in B.A.S. v5.0. Ty for mentioning the bug!
